apiVersion: app.ll.io/v1beta1
kind: MyApp
metadata:
  name: myapp-sample
  annotations:
    old-spec: "spec:
  size: 2
  image: nginx:1.7.9
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002"
spec:
  size: 2
  image: nginx:1.7.9
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002